- hosts: servers
  roles:
    - role: kubelet-service
      systemd_service_name: "kubelet"
      systemd_service_envs:
          - "DOCKER_HOST=tcp://127.0.0.1:2375"
      systemd_service_Unit_Description: Kubelet Manager
      systemd_service_Unit_Requires: flannel.service
      systemd_service_Unit_After: flannel.service
      systemd_service_Service_ExecStartPre:
          - -/usr/bin/docker stop swarm-manager
          - -/usr/bin/docker rm swarm-manager
          - /usr/bin/docker pull swarm
      systemd_service_Service_ExecStart: /usr/bin/docker run -p 2377:2375 --name swarm-manager swarm manage
