---

- name: Download and install etcd
  yum: name=etcd state=present

- name: Configure the etcd env file
  template: src=etcd.j2 dest=/etc/sysconfig/etcd
  notify:
    - restart etcd

- name: Start the etcd service
  service: name=etcd state=started enabled=yes
