- name: Create kubernetes group
  group: gid=1080 name=kube state=present

- name: Create kubernetes user
  user: uid=1080 name=kube group=kube

- name: Create kubernetes floder
  file: path=/usr/local/kubernetes state=directory owner=kube group=kube mode=0755

- name: Create kubernetes cni floder
  file: path=/usr/local/kubernetes/cni state=directory owner=kube group=kube mode=0755

- name: Create kubernetes manifest floder
  file: path=/usr/local/kubernetes/manifests state=directory owner=kube group=kube mode=0755

- name: Copy kubelet
  copy: src=kubelet dest=/usr/local/bin/kubelet owner=kube group=kube mode=0766

- name: Copy kube-proxy
  copy: src=../files/kube-proxy dest=/usr/local/bin/kube-proxy owner=kube group=kube mode=0766

- name: Kubernetes kubeconfig
  template: src=kubeconfig.j2 dest=/usr/local/kubernetes/kubeconfig

- name: Kubernetes config
  template: src=config.j2 dest=/usr/local/kubernetes/config

- name: Kubelet config
  template: src=kubelet.j2 dest=/usr/local/kubernetes/kubelet

- name: Kube-Proxy config
  template: src=proxy.j2 dest=/usr/local/kubernetes/proxy

- name: Copy kubelet.service
  copy: src=kubelet.service dest=/etc/systemd/system/kubelet.service
  notify: restart kubelet

- name: Copy kube-proxy.service
  copy: src=kube-proxy.service dest=/etc/systemd/system/kube-proxy.service
  notify: restart kube-proxy
