---
- name: Be sure docker service stopped
  service: name=docker state=stopped

- name: Remove docker vg
  lvg: vg=docker state=absent force=yes

- name: Remove docker
  yum: name=docker state=removed
