---
# file: roles/common/tasks/main.yml
- name: be sure firewall is stop and disabled
  service: name=firewalld state=stopped enabled=no
  tags: firewall

- name: be sure ntp is installed
  yum: name=ntp state=installed
  notify:
    - restart ntpd
  tags: ntp

- name: be sure ntpd is running and enabled
  service: name=ntpd state=started enabled=yes
  tags: ntp

- name: be sure nfs is installed
  yum: name=nfs-utils state=installed
  notify:
    - restart rpc
    - restart nfs
  tags: nfs

- name: be sure set set -o vi
  lineinfile: dest=/etc/profile line='set -o vi'
  tags: custome
