---
- name: Download and install docker
  yum: name=docker state=present
  tags: docker

- name: Modify docker log driver
  replace:
    dest: /etc/sysconfig/docker
    regexp: '(\s+)*--log-driver=journald*'
    replace: '\1--log-driver=json-file --log-opt max-size=10m --log-opt max-file=3'
    backup: yes
  tags: docker

- name: Start the docker service
  service: name=docker state=started enabled=yes
  tags: docker
